import type { CatalogGroup, RoomKind, UnitLevel } from '../db/types';
import { BEDROOM, KITCHEN, LIVING } from './standards';

/** מפרט מקוצר של פריט ספרייה שמגיע עם האפליקציה. */
export interface SeedItem {
  /** מזהה קבוע — כדי שעדכון האפליקציה לא ייצור כפילויות */
  key: string;
  rooms: RoomKind[];
  group: CatalogGroup;
  name: string;
  glyph: string;
  doors?: number;
  drawers?: number;
  level: UnitLevel;
  /** רוחב ברירת מחדל ורוחבי תקן נוספים */
  w: number;
  widths: number[];
  h: number;
  d: number;
  y: number;
  socle?: number;
  counter?: number;
  note?: string;
}

const K = KITCHEN;
const B = BEDROOM;
const V = LIVING;

/** רוחבי תקן נפוצים לארונות מטבח (מ"מ). */
const NARROW = [150, 200, 300, 350, 400, 450, 500, 600];
const WIDE = [600, 700, 800, 900, 1000, 1200];

const kitchenBase = (
  key: string,
  name: string,
  glyph: string,
  w: number,
  widths: number[],
  extra: Partial<SeedItem> = {},
): SeedItem => ({
  key,
  rooms: ['kitchen'],
  group: 'base',
  name,
  glyph,
  level: 'floor',
  w,
  widths,
  h: K.baseCarcassH,
  d: K.baseDepth,
  y: K.socleH,
  socle: K.socleH,
  counter: K.counterH,
  ...extra,
});

const kitchenUpper = (
  key: string,
  name: string,
  glyph: string,
  w: number,
  widths: number[],
  extra: Partial<SeedItem> = {},
): SeedItem => ({
  key,
  rooms: ['kitchen'],
  group: 'upper',
  name,
  glyph,
  level: 'wall',
  w,
  widths,
  h: K.upperH,
  d: K.upperDepth,
  y: K.upperBottom,
  ...extra,
});

const kitchenTall = (
  key: string,
  name: string,
  glyph: string,
  w: number,
  widths: number[],
  extra: Partial<SeedItem> = {},
): SeedItem => ({
  key,
  rooms: ['kitchen'],
  group: 'tall',
  name,
  glyph,
  level: 'tall',
  w,
  widths,
  h: K.tallH - K.socleH,
  d: K.tallDepth,
  y: K.socleH,
  socle: K.socleH,
  ...extra,
});

export const SEED_CATALOG: SeedItem[] = [
  /* ---------------- מטבח — תחתונים ---------------- */
  kitchenBase('k-base-door1', 'ארגז דלת אחת', 'doors', 450, NARROW, { doors: 1 }),
  kitchenBase('k-base-door2', 'ארגז שתי דלתות', 'doors', 800, WIDE, { doors: 2 }),
  kitchenBase('k-base-dr2', 'ארגז 2 מגירות', 'drawers', 600, [400, 450, 500, 600, 800, 900], {
    drawers: 2,
  }),
  kitchenBase('k-base-dr3', 'ארגז 3 מגירות', 'drawers', 600, [400, 450, 500, 600, 800, 900], {
    drawers: 3,
  }),
  kitchenBase('k-base-dr4', 'ארגז 4 מגירות', 'drawers', 600, [400, 450, 500, 600, 800], {
    drawers: 4,
  }),
  kitchenBase('k-base-mix', 'ארגז דלת ומגירה', 'doorDrawer', 450, NARROW, {
    doors: 1,
    drawers: 1,
  }),
  kitchenBase('k-base-sink', 'ארגז כיור', 'sink', 800, [600, 800, 900, 1000, 1200], {
    note: 'ארגז כיור נבנה בלי מדף ועם חזית מגירה עיוורת מעל',
  }),
  kitchenBase('k-base-hob', 'ארגז כיריים', 'hob', 600, [600, 700, 800, 900], {
    drawers: 2,
    note: 'חיתוך כיריים סטנדרטי בשיש — כ-560×490 מ"מ',
  }),
  kitchenBase('k-base-dw', 'ארגז מדיח', 'dishwasher', 600, [450, 600], {
    note: 'נישת מדיח: רוחב 600, גובה 820 מ"מ',
  }),
  kitchenBase('k-base-oven', 'ארגז תנור', 'oven', 600, [600], {
    note: 'נישת תנור בילד אין: כ-560×590 מ"מ',
  }),
  kitchenBase('k-base-corner-car', 'ארגז פינתי סחרחרה', 'carousel', 900, [800, 900, 1000]),
  kitchenBase('k-base-corner', 'ארגז פינתי דלת', 'corner', 900, [800, 900, 1000]),
  kitchenBase('k-base-open', 'ארגז פתוח', 'open', 400, NARROW),
  kitchenBase('k-base-shutter', 'ארגז תריס', 'shutter', 600, [400, 500, 600]),

  /* ---------------- מטבח — עליונים ---------------- */
  kitchenUpper('k-up-door1', 'עליון דלת אחת', 'doors', 450, NARROW, { doors: 1 }),
  kitchenUpper('k-up-door2', 'עליון שתי דלתות', 'doors', 800, WIDE, { doors: 2 }),
  kitchenUpper('k-up-lift', 'עליון קלאפה', 'lift', 600, [500, 600, 800, 900, 1000], {
    h: 450,
    note: 'מנגנון הרמה — נוח מעל אזור עבודה',
  }),
  kitchenUpper('k-up-glass', 'עליון ויטרינה', 'glass', 600, [400, 500, 600, 800], { doors: 2 }),
  kitchenUpper('k-up-micro', 'ארון מיקרוגל עליון', 'oven', 600, [600], { h: 450 }),
  kitchenUpper('k-up-hood', 'ארון קולט אדים', 'hood', 600, [600, 900], {
    h: 450,
    note: 'תחתית קולט אדים 650–750 מ"מ מעל הכיריים',
  }),
  kitchenUpper('k-up-open', 'מדף פתוח עליון', 'open', 800, WIDE, { h: 350 }),
  kitchenUpper('k-up-shutter', 'עליון תריס', 'shutter', 600, [400, 500, 600]),

  /* ---------------- מטבח — עמודות ---------------- */
  kitchenTall('k-tall-ovenmicro', 'עמודת תנור ומיקרוגל', 'ovenMicro', 600, [600]),
  kitchenTall('k-tall-oven', 'עמודת תנור', 'oven', 600, [600]),
  kitchenTall('k-tall-fridge', 'עמודת מקרר', 'fridge', 700, [600, 700, 800, 900], {
    d: 650,
    note: 'לבדוק עומק המקרר בפועל — לרוב 650–700 מ"מ',
  }),
  kitchenTall('k-tall-pantry', 'עמודת מזווה', 'pantry', 500, [400, 450, 500, 600]),
  kitchenTall('k-tall-door', 'עמודת דלתות', 'doors', 600, [400, 500, 600], { doors: 1 }),
  kitchenTall('k-tall-shutter', 'עמודת תריס', 'shutter', 600, [500, 600]),

  /* ---------------- חדר שינה — ארונות ---------------- */
  {
    key: 'b-wd-door1',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'ארון בגדים דלת אחת',
    glyph: 'doors',
    doors: 1,
    level: 'floor',
    w: 500,
    widths: [400, 450, 500, 600],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
    note: 'עומק 600 מ"מ נדרש לתלייה על מוט; 500 מספיק רק למדפים',
  },
  {
    key: 'b-wd-door2',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'ארון בגדים שתי דלתות',
    glyph: 'doors',
    doors: 2,
    level: 'floor',
    w: 1000,
    widths: [800, 900, 1000, 1200],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
  },
  {
    key: 'b-wd-door3',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'ארון בגדים שלוש דלתות',
    glyph: 'doors',
    doors: 3,
    level: 'floor',
    w: 1500,
    widths: [1350, 1500, 1650, 1800],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
  },
  {
    key: 'b-wd-sliding',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'ארון הזזה',
    glyph: 'sliding',
    level: 'floor',
    w: 1800,
    widths: [1400, 1600, 1800, 2000, 2400, 3000],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
    note: 'ארון הזזה דורש עומק 600 מ"מ לפחות בגלל המסילות',
  },
  {
    key: 'b-wd-hang',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'יחידת תלייה ארוכה',
    glyph: 'hang',
    level: 'floor',
    w: 1000,
    widths: [600, 800, 900, 1000, 1200],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
    note: `מוט תלייה ארוכה בגובה ${B.longHangRod} מ"מ`,
  },
  {
    key: 'b-wd-hang2',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'יחידת תלייה כפולה',
    glyph: 'hangDouble',
    level: 'floor',
    w: 1000,
    widths: [600, 800, 900, 1000, 1200],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
    note: `מוטות בגובה ${B.doubleHangLower} ו-${B.doubleHangUpper} מ"מ`,
  },
  {
    key: 'b-wd-shelves',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'יחידת מדפים',
    glyph: 'shelves',
    level: 'floor',
    w: 500,
    widths: [400, 450, 500, 600, 800],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
    note: 'מרווח מדף לקיפול בגדים 300–400 מ"מ',
  },
  {
    key: 'b-wd-drawers',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'יחידת מגירות פנימיות',
    glyph: 'innerDrawers',
    level: 'floor',
    w: 500,
    widths: [400, 450, 500, 600],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
    note: 'מגירת הלבשה 160 מ"מ, מגירת בגדים 200–250 מ"מ',
  },
  {
    key: 'b-wd-shoes',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'עמודת נעליים',
    glyph: 'shoes',
    level: 'floor',
    w: 400,
    widths: [300, 400, 500, 600],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
  },
  {
    key: 'b-wd-corner',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'ארון פינתי',
    glyph: 'corner',
    doors: 1,
    level: 'floor',
    w: 900,
    widths: [800, 900, 1000],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
  },
  {
    key: 'b-wd-mirror',
    rooms: ['bedroom'],
    group: 'storage',
    name: 'ארון עם מראה',
    glyph: 'mirror',
    level: 'floor',
    w: 500,
    widths: [400, 450, 500, 600],
    h: B.wardrobeH - 80,
    d: B.wardrobeDepth,
    y: 80,
    socle: 80,
  },

  /* ---------------- חדר שינה — רהיטים ---------------- */
  {
    key: 'b-nightstand',
    rooms: ['bedroom'],
    group: 'base',
    name: 'שידת לילה',
    glyph: 'nightstand',
    drawers: 2,
    level: 'floor',
    w: 450,
    widths: [400, 450, 500, 600],
    h: B.nightstandH,
    d: 400,
    y: 0,
  },
  {
    key: 'b-dresser',
    rooms: ['bedroom'],
    group: 'base',
    name: 'שידת מגירות',
    glyph: 'drawers',
    drawers: 4,
    level: 'floor',
    w: 900,
    widths: [600, 800, 900, 1000, 1200],
    h: 800,
    d: 450,
    y: 80,
    socle: 80,
  },
  {
    key: 'b-desk',
    rooms: ['bedroom'],
    group: 'base',
    name: 'שולחן עבודה / איפור',
    glyph: 'desk',
    level: 'floor',
    w: 1200,
    widths: [900, 1000, 1200, 1400, 1600],
    h: 750,
    d: 500,
    y: 0,
    note: 'גובה שולחן עבודה נוח: 730–760 מ"מ',
  },
  {
    key: 'b-bridge',
    rooms: ['bedroom'],
    group: 'upper',
    name: 'גשר עליון',
    glyph: 'doors',
    doors: 2,
    level: 'wall',
    w: 1600,
    widths: [1200, 1400, 1600, 1800, 2000],
    h: B.bridgeH,
    d: 400,
    y: 1900,
    note: 'גשר מעל מיטה — תחתית ב-1900 מ"מ לפחות',
  },
  {
    key: 'b-upper',
    rooms: ['bedroom'],
    group: 'upper',
    name: 'יחידה עליונה',
    glyph: 'doors',
    doors: 1,
    level: 'wall',
    w: 600,
    widths: [400, 500, 600, 800],
    h: B.bridgeH,
    d: 400,
    y: 1900,
  },

  /* ---------------- סלון ---------------- */
  {
    key: 'v-tv-drawers',
    rooms: ['living'],
    group: 'base',
    name: 'מזנון טלוויזיה מגירות',
    glyph: 'drawers',
    drawers: 2,
    level: 'floor',
    w: 1600,
    widths: [1200, 1400, 1600, 1800, 2000, 2400],
    h: V.tvUnitH,
    d: V.tvUnitDepth,
    y: 0,
  },
  {
    key: 'v-tv-doors',
    rooms: ['living'],
    group: 'base',
    name: 'מזנון טלוויזיה דלתות',
    glyph: 'doors',
    doors: 2,
    level: 'floor',
    w: 1600,
    widths: [1200, 1400, 1600, 1800, 2000, 2400],
    h: V.tvUnitH,
    d: V.tvUnitDepth,
    y: 0,
  },
  {
    key: 'v-tv-full',
    rooms: ['living'],
    group: 'base',
    name: 'מזנון עם פאנל טלוויזיה',
    glyph: 'tv',
    level: 'floor',
    w: 2000,
    widths: [1600, 1800, 2000, 2400, 2800],
    h: 1600,
    d: V.tvUnitDepth,
    y: 0,
  },
  {
    key: 'v-storage',
    rooms: ['living'],
    group: 'base',
    name: 'ארון אחסון',
    glyph: 'doors',
    doors: 2,
    level: 'floor',
    w: 900,
    widths: [600, 800, 900, 1000, 1200],
    h: 1000,
    d: 400,
    y: 80,
    socle: 80,
  },
  {
    key: 'v-float-shelf',
    rooms: ['living'],
    group: 'upper',
    name: 'מדף צף',
    glyph: 'slab',
    level: 'wall',
    w: 1200,
    widths: [600, 800, 1000, 1200, 1500, 1800],
    h: V.floatingShelfH,
    d: 250,
    y: 1400,
  },
  {
    key: 'v-wall-unit',
    rooms: ['living'],
    group: 'upper',
    name: 'יחידת קיר תלויה',
    glyph: 'doors',
    doors: 2,
    level: 'wall',
    w: 1000,
    widths: [800, 1000, 1200, 1400],
    h: 400,
    d: V.wallUnitDepth,
    y: 1500,
  },
  {
    key: 'v-vitrine',
    rooms: ['living'],
    group: 'upper',
    name: 'ויטרינה',
    glyph: 'glass',
    doors: 2,
    level: 'wall',
    w: 800,
    widths: [600, 800, 1000],
    h: 1200,
    d: 350,
    y: 900,
  },
  {
    key: 'v-library',
    rooms: ['living'],
    group: 'storage',
    name: 'ספרייה',
    glyph: 'shelves',
    level: 'floor',
    w: 1000,
    widths: [600, 800, 1000, 1200],
    h: 2200,
    d: V.wallUnitDepth,
    y: 80,
    socle: 80,
  },
  {
    key: 'v-panel',
    rooms: ['living'],
    group: 'storage',
    name: 'פאנל חיפוי קיר',
    glyph: 'panel',
    level: 'floor',
    w: 1800,
    widths: [1200, 1500, 1800, 2400, 3000],
    h: 2400,
    d: 60,
    y: 0,
  },
  {
    key: 'v-high-unit',
    rooms: ['living'],
    group: 'storage',
    name: 'מזנון גבוה',
    glyph: 'doors',
    doors: 2,
    level: 'floor',
    w: 800,
    widths: [600, 800, 1000, 1200],
    h: 1800,
    d: 400,
    y: 80,
    socle: 80,
  },

  /* ---------------- זמין בכל חדר ---------------- */
  {
    key: 'any-spacer',
    rooms: ['kitchen', 'living', 'bedroom'],
    group: 'base',
    name: 'מרווח / מילוי',
    glyph: 'spacer',
    level: 'floor',
    w: 100,
    widths: [30, 50, 80, 100, 150, 200, 300],
    h: K.baseCarcassH,
    d: K.baseDepth,
    y: K.socleH,
    socle: K.socleH,
    note: 'מילוי בין ארגז לקיר או בין ארגז לעמודה',
  },
];
