/** האיורים הזמינים לבחירה כשבונים ארגז משלך. */
export const GLYPHS: { key: string; label: string }[] = [
  { key: 'doors', label: 'דלתות' },
  { key: 'drawers', label: 'מגירות' },
  { key: 'doorDrawer', label: 'דלת ומגירה' },
  { key: 'open', label: 'פתוח' },
  { key: 'shelves', label: 'מדפים' },
  { key: 'glass', label: 'ויטרינה' },
  { key: 'lift', label: 'קלאפה' },
  { key: 'shutter', label: 'תריס' },
  { key: 'corner', label: 'פינתי' },
  { key: 'carousel', label: 'סחרחרה' },
  { key: 'sink', label: 'כיור' },
  { key: 'hob', label: 'כיריים' },
  { key: 'oven', label: 'תנור' },
  { key: 'ovenMicro', label: 'תנור ומיקרוגל' },
  { key: 'fridge', label: 'מקרר' },
  { key: 'dishwasher', label: 'מדיח' },
  { key: 'hood', label: 'קולט אדים' },
  { key: 'pantry', label: 'מזווה' },
  { key: 'hang', label: 'תלייה' },
  { key: 'hangDouble', label: 'תלייה כפולה' },
  { key: 'sliding', label: 'הזזה' },
  { key: 'shoes', label: 'נעליים' },
  { key: 'innerDrawers', label: 'מגירות פנימיות' },
  { key: 'mirror', label: 'מראה' },
  { key: 'nightstand', label: 'שידה' },
  { key: 'desk', label: 'שולחן' },
  { key: 'tv', label: 'טלוויזיה' },
  { key: 'panel', label: 'פאנל' },
  { key: 'slab', label: 'מדף צף' },
  { key: 'spacer', label: 'מרווח' },
];
