/** בדיקת עשן לקובץ הבודד: נטען מקובץ, נכנסים, ואין שגיאות. */
import { chromium } from 'playwright';
const SP = new URL('shots/', import.meta.url).pathname;
const b = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await b.newPage({ viewport: { width: 420, height: 900 } });
const errs = [];
page.on('pageerror', (e) => errs.push(String(e)));
page.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
const BUILT = new URL('../dist/easycraft.html', import.meta.url).href;
await page.goto(BUILT, { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.getByLabel('שם משתמש').fill('admin');
await page.getByLabel('סיסמה').fill('admin2026');
await page.getByRole('button', { name: 'כניסה' }).first().click();
await page.waitForTimeout(2000);
const body = await page.innerText('body');
console.log('home has:', ['לקוחות', 'מלאי לוחות', 'הגדרות', 'ספריית'].filter((t) => body.includes(t)).join(', '));
await page.screenshot({ path: SP + 'SMOKE-home.png' });
console.log(errs.length ? 'PAGEERROR ' + errs.slice(0, 3).join(' | ') : 'no page errors');
await b.close();
